# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NearestBuildingsToPoint
                                 A QGIS plugin
 This plug in plots buildings that are closest to a point within a given radius
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-11
        copyright            : (C) 2018 by PSMA
        email                : Beta@psma.com.au
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NearestBuildingsToPoint class from file NearestBuildingsToPoint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nearest_building import NearestBuildingsToPoint
    return NearestBuildingsToPoint(iface)
